setwd("D:/Documents/datascience/data/exdata-data-household_power_consumption")

hpc <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
hpc <- hpc[66637:69516,]
hpc[,2] <- paste(hpc[,1],hpc[,2])
hpc$Time <- strptime(hpc$Time,"%d/%m/%Y%X")

setwd("D:/Documents/datascience/exploratory1")
png(filename = "plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
#plot (1,1)
plot(hpc$Time,hpc$Global_active_power,type="l",xlab="",ylab="Global Active Power")
#plot(1,2)
plot(hpc$Time,hpc$Voltage,type="l",xlab="datetime",ylab="Voltage")
#plot(2,1)
plot(hpc$Time,hpc$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
points(hpc$Time,hpc$Sub_metering_2,col="red",type="l")
points(hpc$Time,hpc$Sub_metering_3,col="blue",type="l")
legend(x="topright",bty="n",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lwd=1,cex=0.85,col=c("black","red","blue"))
#plot(2,2)
plot(hpc$Time,hpc$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()
